README.md, package.json, tailwind-no-resets.config.js
tailwind preflight styles interferes with default DOM styling (this is an issue when use in Storm). export a new css bundle with resets disabled.
J=CLIP-205
TEST=manual
Remove tailwind in test-site, and import the new css bundle. see that it loads the styling as expected.
=> css bundle with tailwind preflight disabled

README.md, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatHeader.tsx, src/components/ChatInput.tsx, src/components/ChatPanel.tsx, src/components/ChatPopUp.tsx, src/components/MessageBubble.tsx, src/hooks/useDefaultHandleApiError.ts, src/utils/withStylelessCssClasses.ts, test-site/package-lock.json, test-site/src/index.css, tests/components/ChatInput.test.tsx, tests/components/ChatPanel.test.tsx, tests/utils/withStylelessCssClasses.ts
use `addMessage` from headless instead of `setMessages` to avoid updating with stale state.
J=CLIP-245
TEST=manual
trigger an invalid API key error upon sending a user message. See that the user's message is rendered as well as the default error message.
=> Ensures user message still render when there's a response error

src/components/ChatInput.tsx, src/components/ChatPanel.tsx, tests/components/ChatInput.test.tsx, tests/components/ChatPopUp.stories.tsx
also add some margin to the first message bubble
J=CLIP-287
TEST=auto&manual
see that send button is disabled when input is empty
=> disable send button on empty input

docs/chat-ui-react.chatinputprops.md, docs/chat-ui-react.chatinputprops.stream.md, src/components/ChatInput.tsx, src/components/ChatPanel.tsx, tests/components/ChatInput.test.tsx, tests/components/ChatPanel.test.tsx
We have decided streaming will be an experimental feature while the bugs are ironed out. This adjusts the components to allow streaming, but not by default.
=> disable streaming by default in ChatPanel and ChatInput

package-lock.json, package.json, scoped-bundle.sh, test-site/package-lock.json
Update the css bundle to include width and height to be 100% for `.yext-chat`
TEST=manual
see that bundle is generated successfully and show up in element inspect tab.
=> Default full width and height for wrapper class yext-chat

THIRD-PARTY-NOTICES, api-extractor.json, package-lock.json, package.json, src/components/ChatPanel.tsx, src/components/ChatPopUp.tsx, src/components/FeedbackButtons.tsx, src/components/Markdown.tsx, src/hooks/useReportAnalyticsEvent.ts, test-site/package-lock.json, tests/__utils__/mocks.ts, tsconfig.json
extract chat-ui-react version to pass into `clientSdk` field in analytic event's payload by setting it through the internal function `addClientSdk` in ChatHeadless. This functionality is wrapped in a hook `useReportAnalyticsEvent`.
Due to the import of `package.json` the structure of `dist/` is reformatted (now all previous files are inside src/ and package.json is included in the respective esm and commonjs folder). As such, the entry points needs to be updated to reflect this.
J=CLIP-309
TEST=manual
see in test-site that clientSdk is passed into the payload with the correct versions (e.g. include the new CHAT_UI_REACT in addition to CHAT_HEADLESS_REACT, CHAT_HEADLESS and CHAT_CORE)
=> pass version for clientSdk

.storybook/main.ts, .storybook/preview.ts, LICENSE, package-lock.json, src/components/ChatPopUp.tsx, tests/components/ChatInput.test.tsx
previous Vite version 4.3.8 (from transitive dep) contains a vulnerability issue flag by semgrep. This PR bumps the version in package-lock.json to a new version that addressed the issue.
Additionally, storybook was broken due to Vite's inability to load css bundle from @yext/chat-ui-react. Updated config to resolve the path to a mock css file since storybook uses tailwind anyway. Also mock out requests to analytics API in storybook.
J=CLIP-327,CLIP-342
TEST=manual
see that storybook is now working, with analytics event requests registered by service worker.
=> fix storybook & fix vulnerability from vite

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatInput.tsx, src/components/ChatPanel.tsx, src/components/MessageBubble.tsx, test-site/package-lock.json
as various issues and complexities arise with supporting glass effects ui for the chat panel, we decide to remove it, following the discussion in this [thread](https://yext.slack.com/archives/C04RFPJ3F3P/p1691093817598079).
Also fix the issue with long continuous text message that requites scrolling from user side (this doesn't apply for text from bot side because tables format may require some horizontal scrolling)
Also explicitly add placeholder font size as that doesn't inherit from the element font size but the **root** font-size.
Additionally react-expanding-textarea package that we use to support text-area resizing is not well maintained and its logic seems to present conflict/issues with HH site. I have decided to migrate over to using a newer package react-textarea-autosize, which …
=> UI update: remove glass effects, fix long continuous message, change textarea-resize lib

test-site/craco.config.js, test-site/package-lock.json, test-site/package.json
test-site was broken with the following errors:
specifically this error:
```
Module not found: Error: Can't resolve './components' in '/Users/ytruong/chat-ui-react/lib/esm/src'
Did you mean 'index.js'?
BREAKING CHANGE: The request './components' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
This is due to CRA 5 (create-react-app v5) internally using webpack 5, which follows the Node.js module resolution algorithm and it requires specifying the file extension. In this case, adding …
=> fix test-site: CRA/webpack file extension issue

.storybook/main.ts, .storybook/preview.ts, package.json, sites-config/ci_config.json, src/components/ChatPanel.tsx, test-site/package-lock.json, test-site/src/App.tsx, tests/__utils__/stories.tsx, tests/components/ChatPanel.test.tsx, tests/components/ChatPopUp.stories.tsx, tests/components/MessageBubble.stories.tsx
ensures that the chat panel scrolls to the top
of a new message, not the bottom. This is relevant for messages that are longer than the chat panel
height.
J=CLIP-580
TEST=manual
ran locally and verified functionality
(skip to 35 seconds to see long message, most of video shows unchanged functionality)
https://github.com/yext/chat-ui-react/assets/18685532/726ed70d-a7e9-4369-841a-1420db1c0b4a 
Change-Id: Ie0537282c91a9762d3cfcdba1d4a7988a61cf5be
=> ChatPanel: Message Scrolling Fix

src/components/ChatPanel.tsx
Previously, ChatPanel produces double-sending error message on initial failure. **This is because React state updates in async/catch operation will NOT be batched.**
As such, state updates from `getNextMessage` function will trigger a re-render first (aka `setCanSendMessage=true and setChatLoadingStatus=false` with no new messages). This would bypass the check below and **send another request for the initial message**
then changes from the first request's `catch` clause get executed, which adds a default error message to state -- stopping this loop. The second request then also error out and run the catch clause, adding a second error message.
Solution:
separate out the check above to its own `fetchInitialMessage` state and manually set that state to false when the useEffect containing …
=> fix duplicate error messages

.eslintrc.js, .prettierignore, src/components/ChatPanel.tsx, src/components/ChatPopUp.tsx, src/components/InitialMessagePopUp.tsx, src/components/index.ts, src/hooks/useFetchInitialMessage.ts, tests/components/ChatPopUp.test.tsx
support a new prop field in `ChatPopUp` call `showInitialMessagePopUp`. If true, `ChatPopUp` will display a popup next to the button showing the initial message. This message popup will NOT appear when once the panel is open (either on load or by manual click) or when there's an error fetching the initial message
Also refactored the fetch initial message into its own custom react hook for reusability
J=CLIP-743
TEST=manual&auto
see that tests passed
see that it works in test site
https://github.com/yext/chat-ui-react/assets/36055303/36e3e07a-e7af-47a1-8ba3-dcd9fed9cb68
=> ChatPopUp: support initial message pop up

tests/__utils__/mocks.ts, tests/components/ChatPopUp.test.tsx
properly mock `"@yext/analytics"` to resolve the error below (although it doesn't affect the unit tests -- it just leave some console errors):
TEST=auto
see that the errors are gone when running the tests
=> Fix analytics mock

LICENSE, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatPanel.tsx, src/components/MessageSuggestions.tsx, test-site/src/App.tsx, tests/components/MessageSuggestions.test.tsx
J=CLIP-883
The UI Library now supports suggested replies that are taken from the Chat API response, not just from the initial configuration. Also adjusts the layout so that suggestions are part of the Input panel and not the Messages panel. See below for an example of how it will look.
**Note:** Suggested Replies are not expected to be available in the production version of the Yext Chat API until the beginning of 2024, due to a deployment freeze for the holidays.
=> add support for Suggested Reply feature

src/components/ChatPanel.tsx
Adjusts the ChatPanel's footer implementation a bit so that we don't use the `&>*>a` targeting for making the text blue.
=> Update footer implementation

package-lock.json, package.json, src/components/ChatPopUp.tsx, src/hooks/useFetchInitialMessage.ts, test-site/package-lock.json, test-site/src/App.tsx
when `openOnLoad` and `showUnreadNotification` prop are both in use, initial message was fetched twice -- once from ChatPopUp component and once from ChatPanel. This is because useFetchInitialMessage doesn't share state between the two component.
This PR updates it so ChatPopUp component only fetch when ChatPanel is not render, otherwise ChatPanel should always do the fetching of the initial message
J=CLIP-1231
TEST=manual
see that it works with both `openOnLoad` and `showUnreadNotification` on
https://github.com/yext/chat-ui-react/assets/36055303/12ccb877-8665-4f8e-a5bc-3e883391f857
=> Bug Fix: double initial fetch message from ChatPopup

package-lock.json, package.json, src/components/ChatInput.tsx
For a clear summary of the issue and the solution, see below:
https://dninomiya.github.io/form-guide/stop-enter-submit
Tested via our dev page using the japanese keyboard - I hit enter and verified that it converted the characters but did not send a message. Subsequently hitting Enter correctly sent the message.
I also double-checked that other keyboards (english) still only require one press of the Enter key, so this should be a completely invisible change to anyone using other languages.
=> Patch input to handle Enter event for japanese keyboards correctly

package-lock.json
Upgrade the transitive dependency vite from v4.4.3 to v4.5.3 to address a vulnerability in the package. Specifically to include this [fix for fs.deny for case insensitive systems](https://github.com/vitejs/vite/blob/v4.5.2/packages/vite/CHANGELOG.md#452-2024-01-19). Note that vite is a transitive dependency for storybook development so this doesn't affect the library build itself.
J=VULN-38716
TEST=auto
Ran unit tests, storybook, and test-site
=> vulnerability fix : Upgrade vite

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatPopUp.tsx, test-site/package-lock.json, tests/components/ChatPopUp.test.tsx
J=CLIP-1273
TEST=auto&manual
added new unit tests
see that behavior works as expected in test-site. Open on load when there are non-initial messages saved in local storage. Otherwise, the panel remain close until user click open.
=> ChatPopUp: Open panel on load when there are saved messages in browser storage

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatPanel.tsx, src/components/ChatPopUp.tsx, src/components/MessageBubble.tsx, test-site/package-lock.json
bump chat-headless-react version to be compatible with the version that supports agent client
also adjusted styling to reduce the margin gap between message bubbles, especially multiple ones from the same source.
J=CLIP-1328
TEST=manual
see it works as expected through test-site using chat-core-aws-connect as the agent client
=> agent client support

src/components/FeedbackButtons.tsx, tailwind.config.js
J=CLIP-1309
TEST=manual
verified on test-site that buttons are only displayed on hover for desktop mode and always displayed for mobile mode
=> display feedback buttons on mobile by default

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/components/ChatInput.tsx, src/components/FeedbackButtons.tsx, tailwind.config.js, test-site/package-lock.json, tests/components/ChatInput.test.tsx
the following changes is missing in main. remerging them:
https://github.com/yext/chat-ui-react/pull/81
https://github.com/yext/chat-ui-react/pull/82
https://github.com/yext/chat-ui-react/pull/83
omitting react-markdown update change because it's ESM only and we support both esm and commonjs right now (https://github.com/yext/chat-ui-react/pull/80)
=> Remerge changes to main

package-lock.json, package.json, test-site/package-lock.json
update rollup version to 3.29.5 (https://github.com/rollup/rollup/releases/tag/v3.29.5) which includes a vulnerability fix
J=VULN-39403,VULN-39404
TEST=manual
built package, smoke test using test-site
=> Address rollup vulnerabilities

package-lock.json, package.json, test-site/package-lock.json
addressed:
-  Cross-site Scripting vulnerability in [rollup](https://github.com/rollup/rollup/releases/tag/v2.79.2) in test-site package: https://yexttest.atlassian.net/browse/VULN-39404?focusedCommentId=1649810
- babel-plugin-polyfill-regenerator issue: https://yexttest.atlassian.net/browse/VULN-38484?focusedCommentId=1649848. Note that updating to eslint-config@1.0.2 didn’t actually update babel-plugin-polyfill-regenerator, doing a manual update of the direct parent dep @babel/plugin-transform-runtime did bump up the polyfill dep to 0.6.3.
J=VULN-39404&VULN-38484
=> address vulnerabilities (rollup, babel)

package-lock.json, package.json, src/components/ChatPanel.tsx, tests/components/ChatPanel.test.tsx
J=CLIP-1675
TEST=manual,auto
verified on test-site that the panel remains at the correct scroll position after being reloaded/opened in another tab. Also verified that multiple bot panels do not override each other scroll position.
added and ran unit test
https://github.com/user-attachments/assets/d3ade9aa-02e0-445b-b32d-ca1926bf5d4b
=> Add support to save chat panel's scroll position

.github/workflows/main.yml
Ubuntu 20.04 for Github Actions is being deprecated and will be fully unsupported on 2025-04-01. Update our semgrep action to the latest version.
=> chat-ui-react: Update main.yml to use semgrep-latest

.gitignore, THIRD-PARTY-NOTICES, package-lock.json, package.json, test-site/package-lock.json, test-site/src/App.tsx, tests/__utils__/mocks.ts
Updates chat-ui-react to use chat-headless-react v0.9.5, allowing us to use the latest version of yext/analytics
J=WAT-4671
TEST=auto, manual
Unit and integration tests pass.
Spun up test-site locally with sandbox model. Was able to make requests and receive responses as expected, confirmed analytics events were going through for responses, impressions, and link clicks.
=> chat-ui-react: update chat-headless-react dependency
